name: Tiny Conversations
favicon: null
layout_spectrum: 0.7662494513206184
typography_spectrum: 0.4553875611163676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.43270054343156517
  lightness: 0.7349691849667579
  saturation: 0.9503299971111119
  rhythmicContrast: 0.35445340047590435
purpose: []
